package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * CustomerType generated by hbm2java
 */
public class CustomerType extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private String name;
	
	private String uuid;
	
	//	private Set customers = new HashSet(0);
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	//	
	//	public Set getCustomers() {
	//		return this.customers;
	//	}
	//	
	//	public void setCustomers(Set customers) {
	//		this.customers = customers;
	//	}
	//	
}
