package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1
import java.util.Date;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.Drug;
import org.openmrs.Encounter;
import org.openmrs.Visit;

/**
 * Sending generated by hbm2java
 */
public class DrugItemOrder extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Drug drug;
	
	private Encounter encounter;
	
	private Visit visit;
	
	private Date date;
	
	private String uuid;
	
	private Integer quantity;
	
	private Sending sending;
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Drug getDrug() {
		return drug;
	}
	
	public void setDrug(Drug Drug) {
		this.drug = Drug;
	}
	
	public Encounter getEncounter() {
		return encounter;
	}
	
	public void setEncounter(Encounter encounter) {
		this.encounter = encounter;
	}
	
	public Visit getVisit() {
		return visit;
	}
	
	public void setVisit(Visit visit) {
		this.visit = visit;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public Sending getSending() {
		return sending;
	}
	
	public void setSending(Sending sending) {
		this.sending = sending;
	}
	
	public Integer getQuantity() {
		return quantity;
	}
	
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
}
