package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

/**
 * ItemsLineId generated by hbm2java
 */
public class ItemsLineId implements java.io.Serializable {
	
	private int itemId;
	
	private int locationId;
	
	public ItemsLineId() {
	}
	
	public ItemsLineId(int itemId, int locationId) {
		this.itemId = itemId;
		this.locationId = locationId;
	}
	
	public int getItemId() {
		return this.itemId;
	}
	
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	
	public int getLocationId() {
		return this.locationId;
	}
	
	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemsLineId))
			return false;
		ItemsLineId castOther = (ItemsLineId) other;
		
		return (this.getItemId() == castOther.getItemId()) && (this.getLocationId() == castOther.getLocationId());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getItemId();
		result = 37 * result + this.getLocationId();
		return result;
	}
	
}
