package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {
	
	private int itemId;
	
	private int orderId;
	
	public OrderDetailId() {
	}
	
	public OrderDetailId(int itemId, int orderId) {
		this.itemId = itemId;
		this.orderId = orderId;
	}
	
	public int getItemId() {
		return this.itemId;
	}
	
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	
	public int getOrderId() {
		return this.orderId;
	}
	
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;
		
		return (this.getItemId() == castOther.getItemId()) && (this.getOrderId() == castOther.getOrderId());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getItemId();
		result = 37 * result + this.getOrderId();
		return result;
	}
	
}
