package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

import org.openmrs.BaseOpenmrsData;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail extends BaseOpenmrsData implements java.io.Serializable {
	
	private OrderDetailId pk;
	
	private Item item;
	
	private PharmacyOrder pharmacyOrder;
	
	private Integer id;
	
	private Integer orderLineQuantity;
	
	private Integer itemSoh;
	
	private Integer itemAmc;
	
	private Double orderLineAmount;
	
	private String uuid;
	
	public OrderDetailId getPk() {
		return this.pk;
	}
	
	public void setPk(OrderDetailId pk) {
		this.pk = pk;
	}
	
	public Item getItem() {
		return this.item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public PharmacyOrder getPharmacyOrder() {
		return this.pharmacyOrder;
	}
	
	public void setPharmacyOrder(PharmacyOrder pharmacyOrder) {
		this.pharmacyOrder = pharmacyOrder;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getOrderLineQuantity() {
		return this.orderLineQuantity;
	}
	
	public void setOrderLineQuantity(Integer orderLineQuantity) {
		this.orderLineQuantity = orderLineQuantity;
	}
	
	public Integer getItemSoh() {
		return this.itemSoh;
	}
	
	public void setItemSoh(Integer itemSoh) {
		this.itemSoh = itemSoh;
	}
	
	public Integer getItemAmc() {
		return this.itemAmc;
	}
	
	public void setItemAmc(Integer itemAmc) {
		this.itemAmc = itemAmc;
	}
	
	public Double getOrderLineAmount() {
		return this.orderLineAmount;
	}
	
	public void setOrderLineAmount(Double orderLineAmount) {
		this.orderLineAmount = orderLineAmount;
	}
	
}
