package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.Person;

/**
 * Orders generated by hbm2java
 */
public class Orders extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Person person;
	
	private Supplier supplier;
	
	private String name;
	
	private Date date;
	
	private Double amount;
	
	private Date dateApprobation;
	
	private Date dateReception;
	
	private String uuid;
	
	private Set orderDetails = new HashSet(0);
	
	private Set receptions = new HashSet(0);
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Person getPerson() {
		return this.person;
	}
	
	public void setPerson(Person person) {
		this.person = person;
	}
	
	public Supplier getSupplier() {
		return this.supplier;
	}
	
	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public Double getAmount() {
		return this.amount;
	}
	
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	
	public Date getDateApprobation() {
		return this.dateApprobation;
	}
	
	public void setDateApprobation(Date dateApprobation) {
		this.dateApprobation = dateApprobation;
	}
	
	public Date getDateReception() {
		return this.dateReception;
	}
	
	public void setDateReception(Date dateReception) {
		this.dateReception = dateReception;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public Set getOrderDetails() {
		return this.orderDetails;
	}
	
	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}
	
	public Set getReceptions() {
		return this.receptions;
	}
	
	public void setReceptions(Set receptions) {
		this.receptions = receptions;
	}
	
}
