package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

/**
 * ReceptionDetailId generated by hbm2java
 */
public class ReceptionDetailId implements java.io.Serializable {
	
	private int receptionId;
	
	private int itemId;
	
	public ReceptionDetailId() {
	}
	
	public ReceptionDetailId(int receptionId, int itemId) {
		this.receptionId = receptionId;
		this.itemId = itemId;
	}
	
	public int getReceptionId() {
		return this.receptionId;
	}
	
	public void setReceptionId(int receptionId) {
		this.receptionId = receptionId;
	}
	
	public int getItemId() {
		return this.itemId;
	}
	
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReceptionDetailId))
			return false;
		ReceptionDetailId castOther = (ReceptionDetailId) other;
		
		return (this.getReceptionId() == castOther.getReceptionId()) && (this.getItemId() == castOther.getItemId());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getReceptionId();
		result = 37 * result + this.getItemId();
		return result;
	}
	
}
