package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.Person;

/**
 * Reception generated by hbm2java
 */
public class Reception extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Person person;
	
	private PharmacyOrder pharmacyOrder;
	
	private Date date;
	
	private String uuid;
	
	private Set receptionDetails = new HashSet(0);
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Person getPerson() {
		return this.person;
	}
	
	public void setPerson(Person person) {
		this.person = person;
	}
	
	public PharmacyOrder getPharmacyOrder() {
		return this.pharmacyOrder;
	}
	
	public void setPharmacyOrder(PharmacyOrder pharmacyOrder) {
		this.pharmacyOrder = pharmacyOrder;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public Set getReceptionDetails() {
		return this.receptionDetails;
	}
	
	public void setReceptionDetails(Set receptionDetails) {
		this.receptionDetails = receptionDetails;
	}
	
}
