package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.Person;
import org.openmrs.Visit;

/**
 * Sending generated by hbm2java
 */
public class Sending extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Customer customer;
	
	private CustomerType customerType;
	
	private Person person;
	
	private Visit visit;
	
	private Date date;
	
	private Double sendingAmount;
	
	private String uuid;
	
	private Date validationDate;
	
	private Set sendingDetails = new HashSet(0);
	
	//Not persistance fields
	private Integer numberOfBatches;
	
	private Integer quantity;
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Customer getCustomer() {
		return this.customer;
	}
	
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	public Person getPerson() {
		return this.person;
	}
	
	public void setPerson(Person person) {
		this.person = person;
	}
	
	public Visit getVisit() {
		return visit;
	}
	
	public void setVisit(Visit visit) {
		this.visit = visit;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public Date getValidationDate() {
		return this.validationDate;
	}
	
	public void setValidationDate(Date date) {
		this.validationDate = date;
	}
	
	public Double getSendingAmount() {
		return this.sendingAmount;
	}
	
	public void setSendingAmount(Double sendingAmount) {
		this.sendingAmount = sendingAmount;
	}
	
	public Set getSendingDetails() {
		return this.sendingDetails;
	}
	
	public void setSendingDetails(Set sendingDetails) {
		this.sendingDetails = sendingDetails;
	}
	
	public Integer getNumberOfBatches() {
		return sendingDetails.size();
	}
	
	public void setNumberOfBatches(Integer numberOfBatches) {
		this.numberOfBatches = numberOfBatches;
	}
	
	public CustomerType getCustomerType() {
		return customerType;
	}
	
	public void setCustomerType(CustomerType customerType) {
		this.customerType = customerType;
	}
	
	public Integer getQuantity() {
		try {
			int number = 0;
			Iterator<SendingDetail> itr = sendingDetails.iterator();
			while (itr.hasNext()) {
				SendingDetail sendingDetail = (SendingDetail) itr.next();
				number = number + sendingDetail.getSendingDetailsQuantity();
			}
			return number;
		}
		catch (Exception e) {
			return 0;
		}
		
	}
	
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
}
