package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

import java.beans.Transient;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;
import org.openmrs.Person;

/**
 * Sending generated by hbm2java
 */
public class Sending extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Customer customer;
	
	private Person person;
	
	private Date date;
	
	private Double sendingAmount;
	
	private String uuid;
	
	private Date validationDate;
	
	private Set sendingDetails = new HashSet(0);
	
	private List<SendingDetail> sendingDetailsList = new ArrayList<SendingDetail>();
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Customer getCustomer() {
		return this.customer;
	}
	
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	public Person getPerson() {
		return this.person;
	}
	
	public void setPerson(Person person) {
		this.person = person;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public Date getValidationDate() {
		return this.validationDate;
	}
	
	public void setValidationDate(Date date) {
		this.validationDate = date;
	}
	
	public Double getSendingAmount() {
		return this.sendingAmount;
	}
	
	public void setSendingAmount(Double sendingAmount) {
		this.sendingAmount = sendingAmount;
	}
	
	public Set getSendingDetails() {
		return this.sendingDetails;
	}
	
	public void setSendingDetails(Set sendingDetails) {
		this.sendingDetails = sendingDetails;
	}
	
	@Transient
	public List<SendingDetail> getSendingDetailsList() {
		return this.sendingDetailsList;
	}
	
	public void setSendingDetailsList(List<SendingDetail> sendingDetails) {
		this.sendingDetailsList = sendingDetails;
	}
	
}
