package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import java.util.Date;
import org.openmrs.BaseOpenmrsData;

/**
 * SendingDetail generated by hbm2java
 */
public class SendingDetail extends BaseOpenmrsData implements java.io.Serializable {
	
	private SendingDetailId pk;
	
	private Item item;
	
	private Sending sending;
	
	private int id;
	
	private String uuid;
	
	private Integer sendingDetailsQuantity;
	
	private Integer sendingDetailsValue;
	
	private String sendingItemBatch;
	
	private Date sendingItemExpiryDate;
	
	public SendingDetailId getPk() {
		return this.pk;
	}
	
	public void setPk(SendingDetailId pk) {
		this.pk = pk;
	}
	
	public Item getItem() {
		return this.item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public Sending getSending() {
		return this.sending;
	}
	
	public void setSending(Sending sending) {
		this.sending = sending;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getSendingDetailsQuantity() {
		return this.sendingDetailsQuantity;
	}
	
	public void setSendingDetailsQuantity(Integer sendingDetailsQuantity) {
		this.sendingDetailsQuantity = sendingDetailsQuantity;
	}
	
	public Integer getSendingDetailsValue() {
		return this.sendingDetailsValue;
	}
	
	public void setSendingDetailsValue(Integer sendingDetailsValue) {
		this.sendingDetailsValue = sendingDetailsValue;
	}
	
	public String getSendingItemBatch() {
		return this.sendingItemBatch;
	}
	
	public void setSendingItemBatch(String sendingItemBatch) {
		this.sendingItemBatch = sendingItemBatch;
	}
	
	public Date getSendingItemExpiryDate() {
		return this.sendingItemExpiryDate;
	}
	
	public void setSendingItemExpiryDate(Date sendingItemExpiryDate) {
		this.sendingItemExpiryDate = sendingItemExpiryDate;
	}
	
}
