package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

/**
 * SendingDetailId generated by hbm2java
 */
public class SendingDetailId implements java.io.Serializable {
	
	private int itemId;
	
	private int sendingId;
	
	public SendingDetailId() {
	}
	
	public SendingDetailId(int itemId, int sendingId) {
		this.itemId = itemId;
		this.sendingId = sendingId;
	}
	
	public int getItemId() {
		return this.itemId;
	}
	
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	
	public int getSendingId() {
		return this.sendingId;
	}
	
	public void setSendingId(int sendingId) {
		this.sendingId = sendingId;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SendingDetailId))
			return false;
		SendingDetailId castOther = (SendingDetailId) other;
		
		return (this.getItemId() == castOther.getItemId()) && (this.getSendingId() == castOther.getSendingId());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getItemId();
		result = 37 * result + this.getSendingId();
		return result;
	}
	
}
