package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import org.openmrs.BaseOpenmrsData;

/**
 * StocktakeDetail generated by hbm2java
 */
public class StocktakeDetail extends BaseOpenmrsData implements java.io.Serializable {
	
	private StocktakeDetailId pk;
	
	private Item item;
	
	private Stocktake stocktake;
	
	private Integer id;
	
	private String uuid;
	
	private Integer itemStock;
	
	private Integer itemPhysicalStock;
	
	private String stocktakeLineComments;
	
	private Integer adjustQuantity;
	
	public StocktakeDetailId getPk() {
		return pk;
	}
	
	public void setPk(StocktakeDetailId pk) {
		this.pk = pk;
	}
	
	public Item getItem() {
		return this.item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public Stocktake getStocktake() {
		return this.stocktake;
	}
	
	public void setStocktake(Stocktake stocktake) {
		this.stocktake = stocktake;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public Integer getItemStock() {
		return this.itemStock;
	}
	
	public void setItemStock(Integer itemStock) {
		this.itemStock = itemStock;
	}
	
	public Integer getItemPhysicalStock() {
		return this.itemPhysicalStock;
	}
	
	public void setItemPhysicalStock(Integer itemPhysicalStock) {
		this.itemPhysicalStock = itemPhysicalStock;
	}
	
	public String getStocktakeLineComments() {
		return this.stocktakeLineComments;
	}
	
	public void setStocktakeLineComments(String stocktakeLineComments) {
		this.stocktakeLineComments = stocktakeLineComments;
	}
	
	public Integer getAdjustQuantity() {
		return this.adjustQuantity;
	}
	
	public void setAdjustQuantity(Integer adjustQuantity) {
		this.adjustQuantity = adjustQuantity;
	}
	
}
