package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

/**
 * StocktakeDetailId generated by hbm2java
 */
public class StocktakeDetailId implements java.io.Serializable {
	
	private int itemId;
	
	private int stocktakeId;
	
	public StocktakeDetailId() {
	}
	
	public StocktakeDetailId(int itemId, int stocktakeId) {
		this.itemId = itemId;
		this.stocktakeId = stocktakeId;
	}
	
	public int getItemId() {
		return this.itemId;
	}
	
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	
	public int getStocktakeId() {
		return this.stocktakeId;
	}
	
	public void setStocktakeId(int stocktakeId) {
		this.stocktakeId = stocktakeId;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StocktakeDetailId))
			return false;
		StocktakeDetailId castOther = (StocktakeDetailId) other;
		
		return (this.getItemId() == castOther.getItemId()) && (this.getStocktakeId() == castOther.getStocktakeId());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getItemId();
		result = 37 * result + this.getStocktakeId();
		return result;
	}
	
}
