package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 3:23:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * Stocktake generated by hbm2java
 */
public class Stocktake extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private PharmacyLocation pharmacyLocation;
	
	private String uuid;
	
	private Date date;
	
	private String name;
	
	private Set stocktakeDetails = new HashSet(0);
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public PharmacyLocation getPharmacyLocation() {
		return this.pharmacyLocation;
	}
	
	public void setPharmacyLocation(PharmacyLocation pharmacyLocation) {
		this.pharmacyLocation = pharmacyLocation;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Set getStocktakeDetails() {
		return this.stocktakeDetails;
	}
	
	public void setStocktakeDetails(Set stocktakeDetails) {
		this.stocktakeDetails = stocktakeDetails;
	}
	
}
