package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.openmrs.BaseOpenmrsData;

/**
 * Stocktake generated by hbm2java
 */
public class Stocktake extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private PharmacyLocation location;
	
	private String uuid;
	
	private Date date;
	
	private String name;
	
	private Set stocktakeDetails = new HashSet(0);
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public PharmacyLocation getLocation() {
		return this.location;
	}
	
	public void setLocation(PharmacyLocation location) {
		this.location = location;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Set getStocktakeDetails() {
		return this.stocktakeDetails;
	}
	
	public void setStocktakeDetails(Set stocktakeDetails) {
		this.stocktakeDetails = stocktakeDetails;
	}
	
}
