package org.openmrs.module.savicspharmacy.api.entity;

// Generated May 7, 2021 2:32:33 AM by Hibernate Tools 4.3.1

import java.util.Date;
import org.openmrs.BaseOpenmrsData;

/**
 * Transaction generated by hbm2java
 */
public class Transaction extends BaseOpenmrsData implements java.io.Serializable {
	
	private Integer id;
	
	private Item item;
	
	private PharmacyLocation location;
	
	private TransactionType transactionType;
	
	private String uuid;
	
	private Date date;
	
	private int transactionTypeId;
	
	private Integer quantity;
	
	private String itemBatch;
	
	private Date itemExpiryDate;
	
	private Integer personId;
	
	private Double amount;
	
	private String status;
	
	private Integer sendingId;
	
	private Integer receptionId;
	
	private Integer stocktakeId;
	
	private Date adjustmentDate;
	
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Item getItem() {
		return this.item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public PharmacyLocation getLocation() {
		return this.location;
	}
	
	public void setLocation(PharmacyLocation location) {
		this.location = location;
	}
	
	public TransactionType getTransactionType() {
		return this.transactionType;
	}
	
	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}
	
	public Date getDate() {
		return this.date;
	}
	
	public void setDate(Date date) {
		this.date = date;
	}
	
	public int getTransactionTypeId() {
		return this.transactionTypeId;
	}
	
	public void setTransactionTypeId(int transactionTypeId) {
		this.transactionTypeId = transactionTypeId;
	}
	
	public Integer getQuantity() {
		return this.quantity;
	}
	
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
	public String getItemBatch() {
		return this.itemBatch;
	}
	
	public void setItemBatch(String itemBatch) {
		this.itemBatch = itemBatch;
	}
	
	public Date getItemExpiryDate() {
		return this.itemExpiryDate;
	}
	
	public void setItemExpiryDate(Date itemExpiryDate) {
		this.itemExpiryDate = itemExpiryDate;
	}
	
	public Integer getPersonId() {
		return this.personId;
	}
	
	public void setPersonId(Integer personId) {
		this.personId = personId;
	}
	
	public Double getAmount() {
		return this.amount;
	}
	
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	
	public String getStatus() {
		return this.status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public Integer getSendingId() {
		return this.sendingId;
	}
	
	public void setSendingId(Integer sendingId) {
		this.sendingId = sendingId;
	}
	
	public Integer getReceptionId() {
		return this.receptionId;
	}
	
	public void setReceptionId(Integer receptionId) {
		this.receptionId = receptionId;
	}
	
	public Integer getStocktakeId() {
		return this.stocktakeId;
	}
	
	public void setStocktakeId(Integer stocktakeId) {
		this.stocktakeId = stocktakeId;
	}
	
	public Date getAdjustmentDate() {
		return this.adjustmentDate;
	}
	
	public void setAdjustmentDate(Date adjustmentDate) {
		this.adjustmentDate = adjustmentDate;
	}
	
}
